import type { Product, Order, AIRecommendation, AIInsight, AuditEvent, AnalyticsData, MerchantMetrics, AIBuyerActivity } from './types.js';

export const FEATURED_PRODUCT_ID = 'prod-wedding-dress-001';
export const CROSS_SELL_PRODUCT_ID = 'prod-earrings-001';

export const products: Product[] = [
  {
    id: 'prod-wedding-dress-001',
    name: 'Wine Satin Wedding Dress',
    description: 'An elegant wine-colored satin wedding dress with a flattering A-line silhouette. Features delicate lace detailing on the bodice and a flowing skirt perfect for your special day.',
    price: 4299,
    originalPrice: 5999,
    category: 'wedding-dresses',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3e446?w=600&h=800&fit=crop',
    ],
    rating: 4.8,
    reviewCount: 124,
    variants: [
      { size: 'S', color: 'Wine', stock: 8, sku: 'WSD-S-WINE' },
      { size: 'M', color: 'Wine', stock: 12, sku: 'WSD-M-WINE' },
      { size: 'L', color: 'Wine', stock: 6, sku: 'WSD-L-WINE' },
      { size: 'M', color: 'Burgundy', stock: 4, sku: 'WSD-M-BURG' },
    ],
    tags: ['wedding', 'satin', 'wine', 'formal'],
    specifications: {
      Fabric: 'Premium Satin',
      Length: 'Floor Length',
      Neckline: 'V-Neck',
      Sleeve: 'Cap Sleeve',
      Care: 'Dry Clean Only',
    },
    aiMatchScore: 94,
    aiReasons: [
      'Within your budget of ₹5,000',
      'Size M available in Wine color',
      'Perfect for wedding occasions',
      'Highest rated in category',
    ],
  },
  {
    id: 'prod-wedding-dress-002',
    name: 'Ivory Lace Bridal Gown',
    description: 'Timeless ivory lace bridal gown with intricate embroidery and a cathedral train.',
    price: 4899,
    category: 'wedding-dresses',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=600&h=800&fit=crop'],
    rating: 4.6,
    reviewCount: 89,
    variants: [
      { size: 'S', color: 'Ivory', stock: 5, sku: 'ILB-S-IV' },
      { size: 'M', color: 'Ivory', stock: 7, sku: 'ILB-M-IV' },
      { size: 'L', color: 'Ivory', stock: 3, sku: 'ILB-L-IV' },
    ],
    tags: ['wedding', 'lace', 'ivory', 'formal'],
    specifications: { Fabric: 'Lace', Length: 'Cathedral', Neckline: 'Sweetheart', Sleeve: 'Sleeveless', Care: 'Dry Clean Only' },
    aiMatchScore: 78,
    aiReasons: ['Within budget', 'Size M available', 'Wedding appropriate', 'Different color preference'],
  },
  {
    id: 'prod-wedding-dress-003',
    name: 'Burgundy Velvet Evening Dress',
    description: 'Luxurious burgundy velvet dress ideal for wedding receptions and evening celebrations.',
    price: 3799,
    category: 'wedding-dresses',
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop'],
    rating: 4.5,
    reviewCount: 67,
    variants: [
      { size: 'M', color: 'Burgundy', stock: 9, sku: 'BVE-M-BURG' },
      { size: 'L', color: 'Burgundy', stock: 5, sku: 'BVE-L-BURG' },
    ],
    tags: ['wedding', 'velvet', 'burgundy', 'evening'],
    specifications: { Fabric: 'Velvet', Length: 'Midi', Neckline: 'Off-Shoulder', Sleeve: 'Long Sleeve', Care: 'Dry Clean Only' },
    aiMatchScore: 85,
    aiReasons: ['Within budget', 'Similar wine tone', 'Size M available', 'Evening wedding suitable'],
  },
  {
    id: 'prod-wedding-dress-004',
    name: 'Rose Gold Sequin Party Dress',
    description: 'Stunning rose gold sequin dress for wedding parties and celebrations.',
    price: 3499,
    category: 'party-wear',
    image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600&h=800&fit=crop'],
    rating: 4.4,
    reviewCount: 45,
    variants: [
      { size: 'S', color: 'Rose Gold', stock: 6, sku: 'RGS-S-RG' },
      { size: 'M', color: 'Rose Gold', stock: 8, sku: 'RGS-M-RG' },
    ],
    tags: ['party', 'sequin', 'rose-gold'],
    specifications: { Fabric: 'Sequin Mesh', Length: 'Knee Length', Neckline: 'Halter', Sleeve: 'Sleeveless', Care: 'Hand Wash' },
    aiMatchScore: 72,
    aiReasons: ['Within budget', 'Size M available', 'Party appropriate', 'Different color tone'],
  },
  {
    id: 'prod-earrings-001',
    name: 'Gold Statement Earrings',
    description: 'Elegant gold-plated statement earrings with crystal accents. Perfect complement to wedding attire.',
    price: 799,
    category: 'earrings',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop'],
    rating: 4.7,
    reviewCount: 203,
    variants: [{ size: 'One Size', color: 'Gold', stock: 45, sku: 'GSE-OS-GOLD' }],
    tags: ['earrings', 'gold', 'wedding', 'accessories'],
    specifications: { Material: 'Gold Plated Brass', Weight: '12g', Closure: 'Push Back', Care: 'Store in pouch' },
  },
  {
    id: 'prod-saree-001',
    name: 'Banarasi Silk Saree',
    description: 'Handwoven Banarasi silk saree with gold zari work, perfect for weddings and festive occasions.',
    price: 8999,
    category: 'sarees',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550195585?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1610030469983-98e550195585?w=600&h=800&fit=crop'],
    rating: 4.9,
    reviewCount: 156,
    variants: [
      { size: 'Free Size', color: 'Maroon', stock: 10, sku: 'BSS-FS-MAR' },
      { size: 'Free Size', color: 'Gold', stock: 8, sku: 'BSS-FS-GOLD' },
    ],
    tags: ['saree', 'silk', 'banarasi', 'wedding'],
    specifications: { Fabric: 'Pure Silk', Length: '6.3 meters', Blouse: 'Included', Care: 'Dry Clean Only' },
  },
  {
    id: 'prod-kurti-001',
    name: 'Embroidered Cotton Kurti',
    description: 'Comfortable cotton kurti with delicate hand embroidery, ideal for casual and semi-formal wear.',
    price: 1299,
    category: 'kurtis',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&h=800&fit=crop'],
    rating: 4.3,
    reviewCount: 78,
    variants: [
      { size: 'S', color: 'White', stock: 15, sku: 'ECK-S-WHT' },
      { size: 'M', color: 'White', stock: 20, sku: 'ECK-M-WHT' },
      { size: 'L', color: 'Blue', stock: 12, sku: 'ECK-L-BLU' },
    ],
    tags: ['kurti', 'cotton', 'casual'],
    specifications: { Fabric: 'Cotton', Length: 'Knee Length', Sleeve: 'Three Quarter', Care: 'Machine Wash' },
  },
  {
    id: 'prod-jeans-001',
    name: 'High-Rise Slim Fit Jeans',
    description: 'Premium denim high-rise slim fit jeans with stretch comfort for all-day wear.',
    price: 2199,
    category: 'jeans',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&h=800&fit=crop'],
    rating: 4.5,
    reviewCount: 312,
    variants: [
      { size: '28', color: 'Indigo', stock: 25, sku: 'HRJ-28-IND' },
      { size: '30', color: 'Indigo', stock: 30, sku: 'HRJ-30-IND' },
      { size: '32', color: 'Black', stock: 18, sku: 'HRJ-32-BLK' },
    ],
    tags: ['jeans', 'denim', 'casual'],
    specifications: { Fabric: '98% Cotton, 2% Elastane', Rise: 'High', Fit: 'Slim', Care: 'Machine Wash' },
  },
  {
    id: 'prod-handbag-001',
    name: 'Leather Crossbody Handbag',
    description: 'Premium leather crossbody handbag with adjustable strap and multiple compartments.',
    price: 3499,
    category: 'handbags',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=600&fit=crop'],
    rating: 4.6,
    reviewCount: 89,
    variants: [
      { size: 'Medium', color: 'Tan', stock: 14, sku: 'LCH-M-TAN' },
      { size: 'Medium', color: 'Black', stock: 20, sku: 'LCH-M-BLK' },
    ],
    tags: ['handbag', 'leather', 'accessories'],
    specifications: { Material: 'Genuine Leather', Dimensions: '25 x 18 x 8 cm', Strap: 'Adjustable', Care: 'Leather conditioner' },
  },
  {
    id: 'prod-necklace-001',
    name: 'Pearl Layered Necklace',
    description: 'Elegant layered pearl necklace with gold-tone chain, perfect for weddings and formal events.',
    price: 1499,
    category: 'necklaces',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop'],
    rating: 4.8,
    reviewCount: 67,
    variants: [{ size: 'Adjustable', color: 'Pearl White', stock: 22, sku: 'PLN-ADJ-PW' }],
    tags: ['necklace', 'pearl', 'wedding'],
    specifications: { Material: 'Freshwater Pearls', Length: '40-45 cm', Clasp: 'Lobster', Care: 'Avoid water' },
  },
  {
    id: 'prod-shoes-001',
    name: 'Embellished Heeled Sandals',
    description: 'Stunning embellished heeled sandals with crystal details, ideal for weddings and parties.',
    price: 2799,
    category: 'shoes',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop'],
    rating: 4.4,
    reviewCount: 54,
    variants: [
      { size: '6', color: 'Gold', stock: 8, sku: 'EHS-6-GOLD' },
      { size: '7', color: 'Gold', stock: 10, sku: 'EHS-7-GOLD' },
      { size: '8', color: 'Silver', stock: 6, sku: 'EHS-8-SIL' },
    ],
    tags: ['shoes', 'heels', 'wedding'],
    specifications: { 'Heel Height': '3 inches', Material: 'Synthetic', Sole: 'Rubber', Care: 'Wipe clean' },
  },
  {
    id: 'prod-jacket-001',
    name: 'Tailored Blazer Jacket',
    description: 'Structured tailored blazer in premium fabric, versatile for office and evening wear.',
    price: 3999,
    category: 'jackets',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop',
    images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop'],
    rating: 4.5,
    reviewCount: 43,
    variants: [
      { size: 'S', color: 'Navy', stock: 7, sku: 'TBJ-S-NAV' },
      { size: 'M', color: 'Navy', stock: 9, sku: 'TBJ-M-NAV' },
      { size: 'L', color: 'Black', stock: 5, sku: 'TBJ-L-BLK' },
    ],
    tags: ['jacket', 'blazer', 'formal'],
    specifications: { Fabric: 'Wool Blend', Fit: 'Slim', Lining: 'Polyester', Care: 'Dry Clean Only' },
  },
];

export const demoOrder: Order = {
  id: 'order-001',
  orderNumber: 'AC-10429',
  productId: FEATURED_PRODUCT_ID,
  productName: 'Wine Satin Wedding Dress',
  productImage: products[0].image,
  amount: 4299,
  quantity: 1,
  size: 'M',
  color: 'Wine',
  status: 'confirmed',
  paymentStatus: 'success',
  createdAt: new Date(),
  customerName: 'Priya Sharma',
  customerEmail: 'priya.sharma@email.com',
  shippingAddress: '42, Green Park Extension, New Delhi - 110016',
  isAiBuyerOrder: true,
  aiMatchScore: 94,
  timeline: [
    { id: 't1', label: 'Order Placed', timestamp: new Date(), status: 'completed' },
    { id: 't2', label: 'Payment Confirmed', timestamp: new Date(), status: 'completed' },
    { id: 't3', label: 'Processing', timestamp: new Date(), status: 'current' },
    { id: 't4', label: 'Shipped', timestamp: new Date(), status: 'pending' },
    { id: 't5', label: 'Delivered', timestamp: new Date(), status: 'pending' },
  ],
};

export const aiRecommendations: AIRecommendation[] = [
  {
    id: 'rec-001',
    type: 'cross-sell',
    title: 'Wedding Dress + Gold Statement Earrings',
    description: 'Customers purchasing wedding dresses are frequently interested in statement earrings. Pairing these products could increase average order value.',
    productIds: [FEATURED_PRODUCT_ID, CROSS_SELL_PRODUCT_ID],
    expectedImpact: 'Increase average order value by 18%',
    revenueImpact: 799,
    status: 'pending',
    createdAt: new Date(),
  },
  {
    id: 'rec-002',
    type: 'bundle',
    title: 'Complete Wedding Look Bundle',
    description: 'Bundle wedding dress with earrings and necklace for a complete bridal look at a discounted price.',
    productIds: [FEATURED_PRODUCT_ID, CROSS_SELL_PRODUCT_ID, 'prod-necklace-001'],
    expectedImpact: 'Boost bundle conversion by 25%',
    revenueImpact: 2299,
    status: 'pending',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'rec-003',
    type: 'upsell',
    title: 'Premium Banarasi Silk Upgrade',
    description: 'Customers browsing wedding dresses may upgrade to premium Banarasi silk sarees for traditional weddings.',
    productIds: ['prod-saree-001'],
    expectedImpact: 'Increase premium category revenue',
    revenueImpact: 4700,
    status: 'approved',
    createdAt: new Date(Date.now() - 172800000),
  },
];

export const aiInsights: AIInsight[] = [
  {
    id: 'insight-001',
    type: 'cross-sell',
    title: 'Cross-sell opportunity detected',
    description: 'Customers purchasing wedding dresses are frequently interested in earrings.',
    impact: 'Potential +₹799 per order',
    createdAt: new Date(),
  },
  {
    id: 'insight-002',
    type: 'pattern',
    title: 'Customer pattern detected',
    description: 'AI Buyer searches for wine-colored wedding attire increased 34% this week.',
    impact: 'Optimize wine color inventory',
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'insight-003',
    type: 'upsell',
    title: 'Upsell opportunity found',
    description: 'Customers with budgets under ₹5,000 often accept accessories when shown at checkout.',
    impact: 'Cart cross-sell conversion: 28%',
    createdAt: new Date(Date.now() - 7200000),
  },
];

export const auditEvents: AuditEvent[] = [
  { id: 'audit-001', timestamp: new Date(Date.now() - 300000), event: 'AI Buyer searched products', actor: 'AI Buyer', status: 'info', relatedProduct: 'Wine Satin Wedding Dress' },
  { id: 'audit-002', timestamp: new Date(Date.now() - 240000), event: 'AI Buyer created cart', actor: 'AI Buyer', status: 'info', relatedProduct: 'Wine Satin Wedding Dress' },
  { id: 'audit-003', timestamp: new Date(Date.now() - 180000), event: 'Purchase policy evaluated', actor: 'System', status: 'info' },
  { id: 'audit-004', timestamp: new Date(Date.now() - 120000), event: 'Purchase approved', actor: 'System', status: 'success', relatedOrder: 'AC-10429' },
  { id: 'audit-005', timestamp: new Date(Date.now() - 60000), event: 'Payment initiated', actor: 'System', status: 'info', relatedOrder: 'AC-10429' },
  { id: 'audit-006', timestamp: new Date(), event: 'Order created', actor: 'System', status: 'success', relatedOrder: 'AC-10429' },
  { id: 'audit-007', timestamp: new Date(), event: 'AI Merchant analyzed order', actor: 'AI Merchant', status: 'info', relatedOrder: 'AC-10429' },
  { id: 'audit-008', timestamp: new Date(), event: 'Cross-sell recommendation generated', actor: 'AI Merchant', status: 'success' },
];

export const merchantMetrics: MerchantMetrics = {
  totalRevenue: 284750,
  aiAttributedRevenue: 4299,
  orders: 156,
  conversionRate: 3.2,
  averageOrderValue: 1825,
  aiBuyerOrders: 1,
};

export const analyticsData: AnalyticsData = {
  revenueTrend: [
    { date: 'Mon', revenue: 32000, aiRevenue: 0 },
    { date: 'Tue', revenue: 28500, aiRevenue: 0 },
    { date: 'Wed', revenue: 35200, aiRevenue: 0 },
    { date: 'Thu', revenue: 41800, aiRevenue: 0 },
    { date: 'Fri', revenue: 38900, aiRevenue: 0 },
    { date: 'Sat', revenue: 45200, aiRevenue: 0 },
    { date: 'Sun', revenue: 4299, aiRevenue: 4299 },
  ],
  ordersTrend: [
    { date: 'Mon', orders: 18, aiOrders: 0 },
    { date: 'Tue', orders: 15, aiOrders: 0 },
    { date: 'Wed', orders: 22, aiOrders: 0 },
    { date: 'Thu', orders: 24, aiOrders: 0 },
    { date: 'Fri', orders: 21, aiOrders: 0 },
    { date: 'Sat', orders: 28, aiOrders: 0 },
    { date: 'Sun', orders: 1, aiOrders: 1 },
  ],
  productPerformance: [
    { name: 'Wine Satin Wedding Dress', revenue: 42990, orders: 10, aiOrders: 1 },
    { name: 'Banarasi Silk Saree', revenue: 35996, orders: 4, aiOrders: 0 },
    { name: 'Gold Statement Earrings', revenue: 15980, orders: 20, aiOrders: 0 },
    { name: 'Embroidered Cotton Kurti', revenue: 12990, orders: 10, aiOrders: 0 },
    { name: 'High-Rise Slim Fit Jeans', revenue: 21990, orders: 10, aiOrders: 0 },
  ],
  conversionMetrics: {
    totalVisitors: 4850,
    aiBuyerSessions: 124,
    conversionRate: 3.2,
    aiConversionRate: 4.8,
    averageOrderValue: 1825,
    aiAverageOrderValue: 4299,
  },
};

export const aiBuyerActivities: AIBuyerActivity[] = [
  { id: 'act-001', type: 'search', query: 'wine-colored wedding dress under ₹5,000 size M', timestamp: new Date(Date.now() - 300000) },
  { id: 'act-002', type: 'view', productId: FEATURED_PRODUCT_ID, productName: 'Wine Satin Wedding Dress', matchScore: 94, timestamp: new Date(Date.now() - 240000) },
  { id: 'act-003', type: 'cart', productId: FEATURED_PRODUCT_ID, productName: 'Wine Satin Wedding Dress', matchScore: 94, timestamp: new Date(Date.now() - 180000) },
  { id: 'act-004', type: 'purchase', productId: FEATURED_PRODUCT_ID, productName: 'Wine Satin Wedding Dress', matchScore: 94, revenue: 4299, timestamp: new Date() },
];

export const DEMO_QUERY = 'I need a wine-colored wedding dress under ₹5,000, size M.';

export const categoryLabels: Record<string, string> = {
  'wedding-dresses': 'Wedding Dresses',
  dresses: 'Dresses',
  sarees: 'Sarees',
  kurtis: 'Kurtis',
  shirts: 'Shirts',
  't-shirts': 'T-Shirts',
  jeans: 'Jeans',
  trousers: 'Trousers',
  jackets: 'Jackets',
  shoes: 'Shoes',
  handbags: 'Handbags',
  earrings: 'Earrings',
  necklaces: 'Necklaces',
  'wedding-accessories': 'Wedding Accessories',
  'party-wear': 'Party Wear',
};

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(price);
}
